Add Postgres database template setup to bin/setup
One less thing to copy and paste (which is error prone) by hand when it can
be done (and updated in one place) through `bin/setup`.

I've included some logic to abort if `createdb` is not available as a shell
command with some error feedback in that case:

> Error: PostgreSQL needs to be installed before setup can be completed.